### ISSUE TITLE
是否能支持下sonar地址的参数的传递

### ISSUE THREAD

**Issue by llllllizili** [xbmlz/sonar-dingtalk-plugin#1]
容器部署的sonarqube,做的端口映射.但内部访问地址为localhost.导致请求失败 无法发送消息,能否支持下sonar地址的定义

**Comment by HuberyChang** [comment]
+1

**Comment by HuberyChang** [comment]
> 容器部署的sonarqube,做的端口映射.但内部访问地址为localhost.导致请求失败 无法发送消息,能否支持下sonar地址的定义

+1

**Comment by metaire** [comment]
+1 最终如何解决嘛

**Comment by llllllizili** [comment]
> +1 最终如何解决嘛

查了查,搞了个py版的,已放仓库了
