### ISSUE TITLE
是否支持代理

### ISSUE THREAD

**Issue by dengdalue** [xbmlz/sonar-dingtalk-plugin#5]
由于我的sonarqube部署在内网，无法直接访问钉钉，请问支持代理吗？如果支持的话怎么配置代理？非常感谢！

**Comment by xbmlz** [comment]
> 由于我的sonarqube部署在内网，无法直接访问钉钉，请问支持代理吗？如果支持的话怎么配置代理？非常感谢！

更新v0.0.2版本就可以了，具体方案查看 [README.md](https://github.com/xbmlz/sonar-dingtalk-plugin/blob/main/README.md)
